//
//  Constants.h
//  Compass
//
//  Created by macbookpro on 10/21/13.
//  Copyright (c) 2013 Clif Alferness. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const NOTE_ACCEPTED;
FOUNDATION_EXPORT NSString *const NOTE_REJECTED;
FOUNDATION_EXPORT NSString *const NOTE_GRAPH_SHIFTED;
FOUNDATION_EXPORT NSString *const NOTE_PREDICT_SHIFTED;
FOUNDATION_EXPORT NSString *const NOTE_GRAPH_RECALCULATED;
FOUNDATION_EXPORT NSString *const NOTE_PREDICT_RECALCULATED;
FOUNDATION_EXPORT NSString *const NOTE_SETTINGS_CHANGED;
FOUNDATION_EXPORT NSString *const NOTE_BGREADING_ADDED;
FOUNDATION_EXPORT NSString *const NOTE_BGREADING_EDITED;
FOUNDATION_EXPORT NSString *const NOTE_FOODREADING_ADDED;
FOUNDATION_EXPORT NSString *const NOTE_FOODREADING_EDITED;
FOUNDATION_EXPORT NSString *const NOTE_INSULINREADING_ADDED;
FOUNDATION_EXPORT NSString *const NOTE_INSULINREADING_EDITED;
FOUNDATION_EXPORT NSString *const NOTE_PENDINGREADING_DELETED;

FOUNDATION_EXPORT NSString *const SETTING_SHOULD_DISPLAY_BG_IN_MMOL_PER_L;
FOUNDATION_EXPORT NSString *const SETTING_INSULIN_SENSITIVITY;
FOUNDATION_EXPORT NSString *const SETTING_INSULIN_DURATION;
FOUNDATION_EXPORT NSString *const SETTING_INSULIN_TYPE;
FOUNDATION_EXPORT NSString *const SETTING_CARB_SENSITIVITY;
FOUNDATION_EXPORT NSString *const SETTING_MILITARY_TIME;
FOUNDATION_EXPORT NSString *const SETTING_15AG_CONSTANT;
FOUNDATION_EXPORT NSString *const SETTING_HA1C_CONSTANT;
FOUNDATION_EXPORT NSString *const SETTING_IDEALBG_MAX;
FOUNDATION_EXPORT NSString *const SETTING_IDEALBG_MIN;
FOUNDATION_EXPORT NSString *const SETTING_SCREEN_CONSTANT;
FOUNDATION_EXPORT NSString *const SETTING_COMPLETED_TUTORIAL;

FOUNDATION_EXPORT int const INSULINTYPE_REGULAR;
FOUNDATION_EXPORT int const INSULINTYPE_GLULISINE;
FOUNDATION_EXPORT int const INSULINTYPE_LISPRO;
FOUNDATION_EXPORT int const INSULINTYPE_ASPART;

FOUNDATION_EXPORT NSString *const INSULINTYPE_STRING_REGULAR;
FOUNDATION_EXPORT NSString *const INSULINTYPE_STRING_GLULISINE;
FOUNDATION_EXPORT NSString *const INSULINTYPE_STRING_LISPRO;
FOUNDATION_EXPORT NSString *const INSULINTYPE_STRING_ASPART;

FOUNDATION_EXPORT NSString *const PLOT_BGESTIMATED;
FOUNDATION_EXPORT NSString *const PLOT_PREDICT;
FOUNDATION_EXPORT NSString *const PLOT_TREND_HA1C;
FOUNDATION_EXPORT NSString *const PLOT_TREND_BG;
FOUNDATION_EXPORT NSString *const PLOT_TREND_15AG;

FOUNDATION_EXPORT int const SECONDS_IN_ONE_MINUTE;
FOUNDATION_EXPORT int const SECONDS_IN_ONE_HOUR;
FOUNDATION_EXPORT int const SECONDS_PER_DAY;
FOUNDATION_EXPORT int const MINUTES_IN_ONE_HOUR;
FOUNDATION_EXPORT int const HOURS_IN_ONE_DAY;
FOUNDATION_EXPORT int const DAYS_IN_ONE_WEEK;

/// (milligrams/deciliter) / (millimoles/liter)
FOUNDATION_EXPORT float const MG_PER_DL_PER_MMOL_PER_L;

FOUNDATION_EXPORT int const BG_EXPIRATION_MINUTES;
FOUNDATION_EXPORT int const FOOD_CURVE_LENGTH_MINUTES;
FOUNDATION_EXPORT int const PREDICT_MINUTES;

FOUNDATION_EXPORT NSString *const ACTION_STRING1;
FOUNDATION_EXPORT NSString *const ACTION_STRING2;
FOUNDATION_EXPORT NSString *const CARBS_STRING;
FOUNDATION_EXPORT NSString *const INSULIN_STRING;
FOUNDATION_EXPORT NSString *const NO_ACTION_STRING;
